version: '3.3'
services:
    postgres:
        container_name: some-postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            - 'postgres-data-2:/var/lib/postgresql/data'
            - '${pwd}/init.sql:/docker-entrypoint-initdb.d/init.sql'
        image: postgres
