CREATE TABLE distributors (
     did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL CHECK (name <> '')
);

INSERT INTO distributors VALUES
    (1, 'ted'),
    (2, 'tim');
